# -*- mode: ruby -*-
# vi: set ft=ruby :

# Simple vagrantfile to setup oracle 12c testbox

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname="orcl12c"
  config.vm.network "private_network", type: "dhcp"
  config.ssh.forward_x11=true
  config.ssh.forward_agent=true
  config.ssh.insert_key=true
  config.ssh.keep_alive=true
  config.vm.define "orcl12c"
  config.vm.network "forwarded_port", guest: 1521, host: 1521 
  config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.name = "orcl12c"
      v.cpus = 2
      v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
  config.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  
  config.vm.provision :ansible do |ansible|
   ansible.playbook = "playbook.yml"
  end

end
