--- 

- name: inst ntpd
  apt: 
    name: ntp
    state: latest
    update_cache: yes

- name: inst named
  apt: 
    name: bind9
    state: latest

- name: inst bind9utils
  apt: 
    name: bind9utils
    state: latest

- template:
    src: '{{playbook_dir}}/roles/dns/templates/named.conf.options.j2'
    dest: /etc/bind/named.conf.options
    owner: root
    group: root
    mode: '0644'

- template:
    src: '{{playbook_dir}}/roles/dns/templates/named.conf.local.j2'
    dest: /etc/bind/named.conf.local
    owner: root
    group: root
    mode: '0644'

- name: create dir for zone files
  file: 
    path: /var/cache/bind/zones 
    state: directory
    owner: root
    group: bind
    mode: 0770

- name: create data dir
  file: 
    path: /var/named/data
    state: directory
    owner: root
    group: bind
    mode: 0770

- name: create dir for zone files
  file: 
    path: /var/cache/bind/master 
    state: directory
    owner: root
    group: bind
    mode: 0770 

- name: create dir for managed keys
  file: 
    path: /var/named/dynamic 
    state: directory
    owner: bind
    group: bind
    mode: 0640

- name: create dir for dnssec keys
  file: 
    path: /etc/bind/keys 
    state: directory
    owner: root
    group: bind
    mode: 0770

- template:
    src: '{{playbook_dir}}/roles/dns/templates/db.localdomain.j2'
    dest: /var/cache/bind/zones/db.localdomain
    owner: root
    group: root
    mode: '0644'

- template:
    src: '{{playbook_dir}}/roles/dns/templates/db.0.0.10.j2'
    dest: /var/cache/bind/zones/db.0.0.10
    owner: root
    group: root
    mode: '0644'

- template:
    src: '{{playbook_dir}}/roles/dns/templates/resolv.conf.d.base.j2'
    dest: /etc/resolvconf/resolv.conf.d/base
    owner: root
    group: root
    mode: '0644'

- name : install iptables
  apt: name=iptables state=present
  tags: iptables

- name : install iptables-persistent
  apt: name=iptables-persistent state=present

- name: iptables conf in place
  template: 
    src: '{{playbook_dir}}/roles/dns/templates/rules.v4.j2'
    dest: /etc/iptables/rules.v4 
    owner: root
    group: root
    mode: 0750

- name: reload iptables
  command: '/bin/sh -c /sbin/iptables-restore -! < /etc/iptables/rules.v4'
  async: 45
  poll: 5

- name: start and enable iptables
  service: 
      name: netfilter-persistent
      enabled: yes

- name: enable named at start
  service: 
    name: bind9
    enabled: yes

- name: Update sysctl.conf
  blockinfile: |
    dest=/etc/sysctl.conf backup=yes
    content='
    # IP Spoofing protection
    net.ipv4.conf.all.rp_filter = 1
    net.ipv4.conf.default.rp_filter = 1
    # Ignore ICMP broadcast requests
    net.ipv4.icmp_echo_ignore_broadcasts = 1
    # Disable source packet routing
    net.ipv4.conf.all.accept_source_route = 0
    net.ipv6.conf.all.accept_source_route = 0 
    net.ipv4.conf.default.accept_source_route = 0
    net.ipv6.conf.default.accept_source_route = 0
    # Ignore send redirects
    net.ipv4.conf.all.send_redirects = 0
    net.ipv4.conf.default.send_redirects = 0
    # Block SYN attacks
    net.ipv4.tcp_syncookies = 1
    net.ipv4.tcp_max_syn_backlog = 2048
    net.ipv4.tcp_synack_retries = 2
    net.ipv4.tcp_syn_retries = 5
    # Log Martians
    net.ipv4.conf.all.log_martians = 1
    net.ipv4.icmp_ignore_bogus_error_responses = 1
    # Ignore ICMP redirects
    net.ipv4.conf.all.accept_redirects = 0
    net.ipv6.conf.all.accept_redirects = 0
    net.ipv4.conf.default.accept_redirects = 0 
    net.ipv6.conf.default.accept_redirects = 0
    # Ignore Directed pings
    net.ipv4.icmp_echo_ignore_all = 1'

- name: reload sysctl 
  shell: /sbin/sysctl -p 

- name: install haveged to help entropy creation
  apt: 
    name: haveged
    state: latest

- name: generate zone signing key
  shell: dnssec-keygen -a RSASHA256 -b 2048 -3 localdomain
  args: 
    chdir: /etc/bind/keys

- name: generate key signing key
  shell: dnssec-keygen -a RSASHA256 -b 2048 -f KSK -3 example.com
  args: 
    chdir: /etc/bind/keys

- name: ownership of keys to named
  file: 
    path: /etc/bind/keys/
    owner: bind
    group: bind
    mode: 0640
    recurse: yes

- name: ownership of key directory
  file: 
    path: /etc/bind/keys
    owner: root
    group: bind
    mode: 0770

- systemd:
    name: bind9.service
    state: started
    enabled: True





