- hosts: all
  become: yes
  gather_facts: yes
  remote_user: root
  pre_tasks:
      - name: install aptitude
        raw: sudo apt-get -y install aptitude
  tasks:
    - name: apt update
      become: yes
      apt:
        upgrade: yes
        update-cache: yes
      when: ansible_os_family=="Debian"
    - name: import gpg key
      become: yes
      apt_key:
        url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
        state: present
    - name: import pg apt repo
      apt_repository:
        repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
        state: present
    - name: apt update
      become: yes
      apt:
        update-cache: yes

    - name: install postgresql-server-9.5
      package: 
        name: postgresql-9.5
        state: latest  
    - name: install postgresql-server-9.5-contrib
      package: 
        name: postgresql-contrib-9.5
        state: latest
    - name: install postgresql-client-9.5
      package: 
        name: postgresql-client-9.5
        state: latest
    - name: install si units 
      package: 
        name: postgresql-9.5-unit
        state: latest
    - name: start and enable
      service: 
          name: postgresql
          enabled: yes
