- hosts: all
  become: yes
  gather_facts: yes
  remote_user: root
  pre_tasks:
      - name: install aptitude
        raw: sudo apt-get -y install aptitude
  tasks:
    - name: apt update
      become: yes
      apt:
        upgrade: yes
        update-cache: yes
      when: ansible_os_family=="Debian"
    - name: inst ntpd
      apt: 
        name: ntp
        state: latest
        update_cache: yes
    - name: import gpg key
      become: yes
      apt_key:
         keyserver: "hkp://keyserver.ubuntu.com:80"
         id: EA312927
         state: present
    - name: import mongo apt repo
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
    - name: apt update
      become: yes
      apt:
        update-cache: yes

    - name: install mongo and tools
      package: 
        name: mongodb-org
        state: latest  

    - name: conf in place
      template: 
        src: '{{playbook_dir}}/templates/mongodb.service.j2'
        dest: /etc/systemd/system/mongodb.service
        owner: root
        group: root
        mode: 0750

    - name: start and enable
      service: 
          name: mongodb.service
          enabled: yes
