- name: set shmmax
  sysctl: name=kernel.shmmax value=4398046511104 reload=yes
- name: set fs.file-max
  sysctl: name=fs.file-max value=6815744 reload=yes
- name: set kernel.shmmni
  sysctl: name=kernel.shmmni value=4096 reload=yes
- name: set kernel.sem
  sysctl: name=kernel.sem value="250 32000 100 128" reload=yes
- name: set kernel.shmall
  sysctl: name=kernel.shmall value=1073741824 reload=yes
- name: set kernel.panic_on_oops
  sysctl: name=kernel.panic_on_oops value=1 reload=yes
- name: set net.core.rmem_default
  sysctl: name=net.core.rmem_default value=262144 reload=yes
- name: set net.core.rmem_max
  sysctl: name=net.core.rmem_max value=4194304 reload=yes
- name: set net.core.wmem_default
  sysctl: name=net.core.wmem_default value=262144 reload=yes
- name: set net.core.wmem_max
  sysctl: name=net.core.wmem_max value=1048576 reload=yes
- name: set net.ipv4.conf.all.rp_filter
  sysctl: name=net.ipv4.conf.all.rp_filter value=2 reload=yes
- name: set net.ipv4.conf.default.rp_filter
  sysctl: name=net.ipv4.conf.default.rp_filter value=2 reload=yes
- name: set fs.aio-max-nr
  sysctl: name=fs.aio-max-nr value=1048576 reload=yes
- name: set net.ipv4.ip_local_port_range
  sysctl: name=net.ipv4.ip_local_port_range value="9000 65500" reload=yes

# networking part

- name: Update sysctl.conf
  blockinfile: 
    dest: /etc/sysctl.conf
    block: |
      # IP Spoofing protection
      net.ipv4.conf.all.rp_filter = 1
      net.ipv4.conf.default.rp_filter = 1
      # Ignore ICMP broadcast requests
      net.ipv4.icmp_echo_ignore_broadcasts = 1
      # Disable source packet routing
      net.ipv4.conf.all.accept_source_route = 0
      net.ipv6.conf.all.accept_source_route = 0 
      net.ipv4.conf.default.accept_source_route = 0
      net.ipv6.conf.default.accept_source_route = 0
      # Ignore send redirects
      net.ipv4.conf.all.send_redirects = 0
      net.ipv4.conf.default.send_redirects = 0
      # Block SYN attacks
      net.ipv4.tcp_syncookies = 1
      net.ipv4.tcp_max_syn_backlog = 2048
      net.ipv4.tcp_synack_retries = 2
      net.ipv4.tcp_syn_retries = 5
      # Log Martians
      net.ipv4.conf.all.log_martians = 1
      net.ipv4.icmp_ignore_bogus_error_responses = 1
      # Ignore ICMP redirects
      net.ipv4.conf.all.accept_redirects = 0
      net.ipv6.conf.all.accept_redirects = 0
      net.ipv4.conf.default.accept_redirects = 0 
      net.ipv6.conf.default.accept_redirects = 0
      # Ignore Directed pings
      net.ipv4.icmp_echo_ignore_all = 1'
    backup: yes

- name: reload sysctl 
  shell: /sbin/sysctl -p
      