- name: packages
  yum: pkg={{item}} state=latest
  with_items:
    - binutils
    - compat-libcap1
    - compat-libstdc++-33
    - compat-libstdc++-33.i686
    - glibc
    - glibc.i686
    - glibc-devel
    - glibc-devel.i686
    - ksh
    - libaio
    - libaio.i686
    - libaio-devel
    - libaio-devel.i686
    - libX11
    - libX11.i686
    - libXau
    - libXau.i686
    - libXi
    - libXi.i686
    - libXtst
    - libXtst.i686
    - libgcc
    - libgcc.i686
    - libstdc++
    - libstdc++.i686
    - libstdc++-devel
    - libstdc++-devel.i686
    - libxcb
    - libxcb.i686
    - make
    - nfs-utils
    - net-tools
    - smartmontools
    - sysstat
    - unixODBC
    - unixODBC-devel
    - gcc
    - gcc-c++
    - libXext
    - libXext.i686
    - zlib-devel
    - zlib-devel.i686
    - unzip
