- name: oracle12c pamconf
  lineinfile:
    dest: /etc/pam.d/login
    state: present
    line: "session required pam_limits.so"

- name: oracle12c limits
  lineinfile:
    dest: /etc/security/limits.conf
    state: present
    line: "{{item}}"
  with_items:    
   - "oracle   soft   nofile  1024"
   - "oracle   hard   nofile  65536"
   - "oracle   soft   nproc   16384"
   - "oracle   hard   nproc   16384"
   - "oracle   soft   stack   10240"
   - "oracle   hard   stack   32768"
   - "oracle   hard   memlock 134217728"
   - "oracle   soft   memlock 134217728"
