---

- name : install iptables
  apt: name=iptables state=present
  tags: iptables

- name : install iptables-persistent
  apt: name=iptables-persistent state=present
  tags: iptables

- name: conf in place
  template: 
    src: '{{playbook_dir}}/templates/rules.v4.j2'
    dest: /etc/iptables/rules.v4 
    owner: root
    group: root
    mode: 0750
  tags: iptables

- name: start and enable iptables
  service: 
      name: netfilter-persistent
      enabled: yes
  tags: iptables

- name: restore iptables conf
  command: "/bin/sh -c '/sbin/iptables-restore < /etc/iptables/rules.v4'"
  tags: iptables






