- hosts: databases
  become: yes
  gather_facts: yes
  remote_user: root
  pre_tasks:
      - name: install aptitude
        raw: sudo apt-get -y install aptitude
  tasks:
    - name: apt update
      become: yes
      apt:
          upgrade: yes
          update-cache: yes
      when: ansible_os_family=="Debian"
    - name: install mariadb-server
      package: name=mariadb-server state=latest
    - template: 
        src: '{{playbook_dir}}/templates/mysql_secure.sh.j2'
        dest: /root/secure_mysql.sh
        owner: root
        group: root
        mode: 0700
    - name: exec secure mysql installation
      command: /root/secure_mysql.sh
