- name: ntp server setup
  hosts: all
  roles:
    - dns
  become: yes
  gather_facts: yes
  remote_user: root
  handlers: 
      - include: '{{playbook_dir}}/handlers/main.yml'
  pre_tasks:
      - name: install aptitude
        raw: sudo apt-get -y install aptitude
  tasks:
    - name: apt update
      become: yes
      apt:
        upgrade: yes
        update-cache: yes
      when: ansible_os_family=="Debian"
