# -*- mode: ruby -*-
# vi: set ft=ruby :

# Simple vagrantfile to setup postgresql testing playgroud

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname="ns2"
  config.vm.network "private_network", ip: "10.0.0.11"
  config.ssh.forward_x11=false
  config.ssh.insert_key=true
  config.ssh.keep_alive=true
  config.vm.define "dns"
  config.vm.provider "virtualbox" do |v|
   v.memory = 256 
   v.name = "ns2"
   v.cpus = 1 
   v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
   config.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.provision :shell, :inline => "apt-get install python -y"
  config.vm.provision :ansible do |ansible|
   ansible.playbook = "playbook.yml"
  end
end
