# -*- mode: ruby -*-
# vi: set ft=ruby :

# Simple vagrantfile to setup postgresql testing playgroud

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.hostname="nginx"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8081
  config.ssh.forward_x11=true
  config.ssh.insert_key=true
  config.ssh.keep_alive=true
  config.vm.define "web"
  config.vm.provider "virtualbox" do |v|
   v.memory = 1024
   v.name = "lemp"
   v.cpus = 1
   v.customize ["modifyvm", :id, "--cpuexecutioncap", "75"]
   config.vm.synced_folder ".", "/vagrant", disabled: "true"
  end
  config.vm.provision :ansible do |ansible|
   ansible.playbook = "playbook.yml"
  end
end
